title: Brady Claypool # your name (or website title) here
logo: "/images/Back.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior in Management Information Systems at Iowa State University
  Treasurer of the Game Development Club
  <br><br>
  Email: claypool@iastate.edu
  <br><br>
  <a href="https://poolofclay33.github.io/">Home Page</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
